<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>McDungeonsGitBackup</AssemblyName>
    <RootNamespace>McDungeonsGitBackup.App</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <EnableCompressionInSingleFile Condition="'$(SelfContained)' == 'true'">true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\McDungeonsGitBackup.Core\McDungeonsGitBackup.Core.csproj" />
  </ItemGroup>
</Project>
